import { useEffect,useState } from "react";import ProductGrid from "../components/product/ProductGrid";import { useProductCategories,useProducts } from "../features/products/useProducts";
const SIZE=20;
function ProductGridSkeleton(){return <div className="product-grid" aria-label="Loading products">{Array.from({length:SIZE}).map((_,i)=><div className="product-card product-card--skeleton" key={i}><div className="skeleton skeleton--image"/><div className="product-card__body"><div className="skeleton skeleton--small"/><div className="skeleton skeleton--title"/><div className="skeleton skeleton--text"/></div></div>)}</div>}
export default function HomePage(){const[searchTerm,setSearchTerm]=useState("");const[query,setQuery]=useState("");const[selectedCategory,setSelectedCategory]=useState("all");const[currentPage,setCurrentPage]=useState(0);useEffect(()=>{const id=setTimeout(()=>{setQuery(searchTerm.trim());setCurrentPage(0);},300);return()=>clearTimeout(id);},[searchTerm]);useEffect(()=>setCurrentPage(0),[selectedCategory]);const{data,isLoading,isError,error,refetch,isFetching}=useProducts({q:query,category:selectedCategory,page:currentPage,size:SIZE});const{data:categoriesData}=useProductCategories();
const categories=Array.isArray(categoriesData)
  ? categoriesData
  : Array.isArray(categoriesData?.content)
    ? categoriesData.content
    : Array.isArray(categoriesData?.categories)
      ? categoriesData.categories
      : [];const products=data?.content||[];const totalPages=Math.max(1,data?.totalPages||1);const total=data?.totalElements||0;const first=total===0?0:currentPage*SIZE+1;const last=Math.min((currentPage+1)*SIZE,total);return <main><section className="hero"><div className="page-container hero__content"><div className="hero__text"><p className="hero__eyebrow">Cloud-native shopping experience</p><h1>Welcome to Boutique</h1><p>Discover products served by our Spring Boot microservices with live stock information from the Inventory Service.</p><a className="hero__button" href="#products">Shop products</a></div><div className="hero__visual"><img src="/static/icons/Hipster_HeroLogo.svg" alt="Boutique"/></div></div></section><section className="products-section" id="products"><div className="page-container"><div className="section-heading"><div><p className="section-heading__eyebrow">Product catalogue</p><h2>Featured products</h2></div>{!isLoading&&!isError&&<span className="section-heading__count">{total} {total===1?"product":"products"}</span>}</div><div className="product-filters"><label className="product-filters__field"><span>Search</span><input type="search" placeholder="Search products, categories or SKU..." value={searchTerm} onChange={e=>setSearchTerm(e.target.value)}/></label><label className="product-filters__field"><span>Category</span><select value={selectedCategory} onChange={e=>setSelectedCategory(e.target.value)}><option value="all">All categories</option>{categories.map(c=><option key={c} value={c}>{c}</option>)}</select></label></div>{isLoading&&<ProductGridSkeleton/>}{isError&&<div className="error-state" role="alert"><h2>Unable to load products</h2><p>{error?.message||"The Product Service could not be reached."}</p><button type="button" onClick={()=>refetch()} disabled={isFetching}>{isFetching?"Retrying...":"Try again"}</button></div>}{!isLoading&&!isError&&products.length===0&&<div className="empty-state"><h2>No matching products</h2><p>Try another search term or category.</p></div>}{!isLoading&&!isError&&products.length>0&&<><p className="pagination-summary">Showing {first}–{last} of {total} products</p><ProductGrid products={products}/><nav className="pagination"><button type="button" disabled={currentPage===0} onClick={()=>setCurrentPage(p=>Math.max(0,p-1))}>Previous</button><span>Page {currentPage+1} of {totalPages}</span><button type="button" disabled={currentPage+1>=totalPages} onClick={()=>setCurrentPage(p=>p+1)}>Next</button></nav></>}</div></section></main>}
